/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class cargarCliente extends javax.swing.JFrame {

    /**
     * Creates new form cargarCliente
     */
    public cargarCliente() {
        initComponents();
        setSize(575,580);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_UsuarioActual1 = new javax.swing.JLabel();
        btn_mainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nomApellidoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        txt_dniCliente = new javax.swing.JTextField();
        txt_direccionCliente = new javax.swing.JTextField();
        txt_provinciaCliente = new javax.swing.JTextField();
        txt_localidadCliente = new javax.swing.JTextField();
        txt_cpcliente = new javax.swing.JTextField();
        txt_telefonoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_UsuarioActual1.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        label_UsuarioActual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_UsuarioActual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        label_UsuarioActual1.setText("Admin");
        label_UsuarioActual1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(label_UsuarioActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 12, 158, 56));

        btn_mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono-de-inicio-silueta.png"))); // NOI18N
        btn_mainMenu.setText("MENU PRINCIPAL");
        btn_mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mainMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btn_mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 169, 56));

        jLabel1.setText("DNI:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 551, -1));

        jLabel2.setText("Nombre y Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, 551, -1));

        jLabel3.setText("Direccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 262, -1));

        txt_nomApellidoCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_nomApellidoCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_nomApellidoCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_nomApellidoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomApellidoClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomApellidoClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nomApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 551, 30));

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 338, 266, -1));

        jLabel4.setText("Codigo Postal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 338, 266, -1));

        jLabel7.setText("Localidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 276, 260, -1));

        jLabel8.setText("Provincia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 276, 266, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 551, 10));

        jButton1.setFont(new java.awt.Font("Nimbus Mono L", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-derecha.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 487, -1, 56));

        txt_dniCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_dniCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_dniCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_dniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dniClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dniClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_dniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 551, 30));

        txt_direccionCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_direccionCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_direccionCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_direccionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_direccionClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_direccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 234, 551, 30));

        txt_provinciaCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_provinciaCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_provinciaCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_provinciaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_provinciaClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_provinciaClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_provinciaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 296, 266, 30));

        txt_localidadCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_localidadCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_localidadCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_localidadCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_localidadClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_localidadClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_localidadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 296, 266, 30));

        txt_cpcliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_cpcliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_cpcliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_cpcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cpclienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cpclienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_cpcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 364, 266, 30));

        txt_telefonoCliente.setMaximumSize(new java.awt.Dimension(4, 22));
        txt_telefonoCliente.setMinimumSize(new java.awt.Dimension(4, 22));
        txt_telefonoCliente.setPreferredSize(new java.awt.Dimension(4, 22));
        txt_telefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefonoClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_telefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 364, 266, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainMenuMouseClicked
        menuPrincipal mp = new menuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mainMenuMouseClicked

    private void txt_nomApellidoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomApellidoClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomApellidoClienteKeyPressed

    private void txt_nomApellidoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomApellidoClienteKeyTyped
    }//GEN-LAST:event_txt_nomApellidoClienteKeyTyped

    private void txt_dniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniClienteKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txt_dniClienteKeyTyped

    private void txt_dniClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniClienteKeyPressed

    private void txt_direccionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionClienteKeyTyped

    private void txt_direccionClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionClienteKeyPressed

    private void txt_provinciaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provinciaClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_provinciaClienteKeyTyped

    private void txt_provinciaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provinciaClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_provinciaClienteKeyPressed

    private void txt_localidadClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_localidadClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localidadClienteKeyTyped

    private void txt_localidadClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_localidadClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localidadClienteKeyPressed

    private void txt_cpclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cpclienteKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txt_cpclienteKeyTyped

    private void txt_cpclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cpclienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpclienteKeyPressed

    private void txt_telefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoClienteKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txt_telefonoClienteKeyTyped

    private void txt_telefonoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoClienteKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
       if(txt_nomApellidoCliente.getText().length()== 0 ||
          txt_dniCliente.getText().length()==0 ||
          txt_cpcliente.getText().length()==0 ||
          txt_localidadCliente.getText().length()==0 ||
          txt_provinciaCliente.getText().length()==0 ||
          txt_telefonoCliente.getText().length()==0 ||
          txt_direccionCliente.getText().length()==0 ){
           JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
       } else {
          seleccionarMotivo carProducto = new seleccionarMotivo();
          carProducto.setVisible(true);
          dispose();
       }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_UsuarioActual1;
    private javax.swing.JTextField txt_cpcliente;
    private javax.swing.JTextField txt_direccionCliente;
    private javax.swing.JTextField txt_dniCliente;
    private javax.swing.JTextField txt_localidadCliente;
    private javax.swing.JTextField txt_nomApellidoCliente;
    private javax.swing.JTextField txt_provinciaCliente;
    private javax.swing.JTextField txt_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
