/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

import javax.swing.JOptionPane;
import maxselectdds.Metodos_sql;


/**
 *
 * @author erick
 */
public class cargarCliente extends javax.swing.JFrame {

    static String dniNuevo;
    static boolean esNuevo;

    Metodos_sql metodos = new Metodos_sql();
    /**
     * Creates new form cargarCliente
     */
    public cargarCliente() {
        initComponents();
        setSize(575,580);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_UsuarioActual1 = new javax.swing.JLabel();
        btn_mainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomyap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        txtProv = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_UsuarioActual1.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        label_UsuarioActual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_UsuarioActual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        label_UsuarioActual1.setText("Admin");
        label_UsuarioActual1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(label_UsuarioActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 12, 158, 56));

        btn_mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono-de-inicio-silueta.png"))); // NOI18N
        btn_mainMenu.setText("MENU PRINCIPAL");
        btn_mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mainMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btn_mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 169, 56));

        jLabel1.setText("DNI:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 551, -1));

        jLabel2.setText("Nombre y Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, 551, -1));

        jLabel3.setText("Direccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 262, -1));

        txtNomyap.setMaximumSize(new java.awt.Dimension(4, 22));
        txtNomyap.setMinimumSize(new java.awt.Dimension(4, 22));
        txtNomyap.setPreferredSize(new java.awt.Dimension(4, 22));
        txtNomyap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomyapKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomyapKeyPressed(evt);
            }
        });
        getContentPane().add(txtNomyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 551, 30));

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 338, 266, -1));

        jLabel4.setText("Codigo Postal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 338, 266, -1));

        jLabel7.setText("Localidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 276, 260, -1));

        jLabel8.setText("Provincia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 276, 266, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 551, 10));

        jButton1.setFont(new java.awt.Font("Nimbus Mono L", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-derecha.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 487, -1, 56));

        txtDNI.setMaximumSize(new java.awt.Dimension(4, 22));
        txtDNI.setMinimumSize(new java.awt.Dimension(4, 22));
        txtDNI.setPreferredSize(new java.awt.Dimension(4, 22));
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 551, 30));

        txtDir.setMaximumSize(new java.awt.Dimension(4, 22));
        txtDir.setMinimumSize(new java.awt.Dimension(4, 22));
        txtDir.setPreferredSize(new java.awt.Dimension(4, 22));
        txtDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDirKeyPressed(evt);
            }
        });
        getContentPane().add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 234, 551, 30));

        txtProv.setMaximumSize(new java.awt.Dimension(4, 22));
        txtProv.setMinimumSize(new java.awt.Dimension(4, 22));
        txtProv.setPreferredSize(new java.awt.Dimension(4, 22));
        txtProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProvKeyPressed(evt);
            }
        });
        getContentPane().add(txtProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 296, 266, 30));

        txtLoc.setMaximumSize(new java.awt.Dimension(4, 22));
        txtLoc.setMinimumSize(new java.awt.Dimension(4, 22));
        txtLoc.setPreferredSize(new java.awt.Dimension(4, 22));
        txtLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLocKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLocKeyPressed(evt);
            }
        });
        getContentPane().add(txtLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 296, 266, 30));

        txtCP.setMaximumSize(new java.awt.Dimension(4, 22));
        txtCP.setMinimumSize(new java.awt.Dimension(4, 22));
        txtCP.setPreferredSize(new java.awt.Dimension(4, 22));
        txtCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPKeyPressed(evt);
            }
        });
        getContentPane().add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 364, 266, 30));

        txtTel.setMaximumSize(new java.awt.Dimension(4, 22));
        txtTel.setMinimumSize(new java.awt.Dimension(4, 22));
        txtTel.setPreferredSize(new java.awt.Dimension(4, 22));
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 364, 266, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainMenuMouseClicked
        menuPrincipal mp = new menuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mainMenuMouseClicked

    private void txtNomyapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomyapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomyapKeyPressed

    private void txtNomyapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomyapKeyTyped
    }//GEN-LAST:event_txtNomyapKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyPressed

    private void txtDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirKeyTyped

    private void txtDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirKeyPressed

    private void txtProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvKeyTyped

    private void txtProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvKeyPressed

    private void txtLocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocKeyTyped

    private void txtLocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocKeyPressed

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtCPKeyTyped

    private void txtCPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPKeyPressed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
       if(txtNomyap.getText().length()== 0 ||
          txtDNI.getText().length()==0 ||
          txtCP.getText().length()==0 ||
          txtLoc.getText().length()==0 ||
          txtProv.getText().length()==0 ||
          txtTel.getText().length()==0 ||
          txtDir.getText().length()==0 ){
           dniNuevo = txtDNI.getText();
           esNuevo = true;
           JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
       } else {
          int i = metodos.guardar(txtDNI.getText(), txtNomyap.getText(), txtDir.getText(), txtLoc.getText(), txtProv.getText(), txtTel.getText(), txtCP.getText());
            if(i > 0){
            JOptionPane.showMessageDialog(this,"El cliente fue cargado con exito!");
            seleccionarMotivo carProducto = new seleccionarMotivo();
            carProducto.setVisible(true);
            dispose();
            dniNuevo = txtDNI.getText();
            esNuevo = true;
            
        }else{
            JOptionPane.showMessageDialog(this,"No se pudieron guardar los datos...");
        }
       }       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargarCliente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_UsuarioActual1;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtNomyap;
    private javax.swing.JTextField txtProv;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
    
    
}
