/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class seleccionarMotivo extends javax.swing.JFrame {

    /**
     * Creates new form cargarProducto
     */
    public seleccionarMotivo() {
        initComponents();
        setResizable(false);
        setSize(575,300);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_finalizar = new javax.swing.JButton();
        btn_mainMenu = new javax.swing.JButton();
        label_UsuarioActual1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        box_motivos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_finalizar.setFont(new java.awt.Font("Nimbus Mono L", 1, 18)); // NOI18N
        btn_finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marca-de-verificacion.png"))); // NOI18N
        btn_finalizar.setText("FINALIZAR");
        btn_finalizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_finalizarMouseClicked(evt);
            }
        });
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finalizar);
        btn_finalizar.setBounds(390, 200, 169, 56);

        btn_mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono-de-inicio-silueta.png"))); // NOI18N
        btn_mainMenu.setText("MENU PRINCIPAL");
        btn_mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mainMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btn_mainMenu);
        btn_mainMenu.setBounds(12, 12, 190, 56);

        label_UsuarioActual1.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        label_UsuarioActual1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_UsuarioActual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        label_UsuarioActual1.setText("Admin");
        label_UsuarioActual1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(label_UsuarioActual1);
        label_UsuarioActual1.setBounds(405, 12, 158, 56);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(12, 74, 551, 10);

        box_motivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un motivo por favor", "Falla en Termotanque", "Falla en Calefon", "Falla en Anafe", "Consulta tecnica", "Consulta comercial", "Consulta administrativa", "Consulta de garantia", "Otros motivos" }));
        getContentPane().add(box_motivos);
        box_motivos.setBounds(12, 122, 551, 23);

        jLabel1.setText("Seleccione un motivo de llamada:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 102, 192, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 580, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizarMouseClicked
        /* Con esto hay que confirmar los datos cargados 
        
        
        
        */
        
        
        /*Mensaje de Exito*/
        JOptionPane.showMessageDialog(this, "Llamada registrada correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        
        
        /*Volver al menu principal*/
        menuPrincipal mp = new menuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_finalizarMouseClicked

    private void btn_mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainMenuMouseClicked
        menuPrincipal mp = new menuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mainMenuMouseClicked

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionarMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionarMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionarMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionarMotivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionarMotivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_motivos;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_UsuarioActual1;
    // End of variables declaration//GEN-END:variables
}
